name: MinecraftAPI
main: me.yinight.MinecraftAPI
version: 1.0
api-version: 1.20
author: Yinight
commands:
  minecraftapi:
    description: 控制 MinecraftAPI 插件
    usage: /minecraftapi debug
    permission: minecraftapi.use
    permission-message: 你没有权限使用这个指令
