name: MinecraftAPI
main: me.yinight.MinecraftAPI
version: 1.0.1
api-version: 1.21
author: Yinight
commands:
  minecraftapi:
    description: 控制 MinecraftAPI 插件
    usage: /minecraftapi [debug|start|stop|check|reload]
    permission: minecraftapi.admin
    permission-message: 你没有权限使用这个指令
